### PR TITLE
Improve spdb memtable performance (#298)

### PR DESCRIPTION
**Pull request by ayulas**
review already done by @hilikspdb for that version

### CODE REVIEW

**Comment by ayulas** [comment]
@erez-speedb @Yuval-Ariel can you pls run tests

**Comment by Yuval-Ariel** [comment]
@ayulas plz fix failed Check buck targets test

**Comment by ayulas** [comment]
fixed

**Review by Yuval-Ariel — APPROVED** [review]

**Comment by ayulas** [comment]
@erez-speedb , @Yuval-Ariel  pls check. it is rebased on the 298

**Review by Yuval-Ariel — APPROVED** [review]

**Review by hilikspdb — COMMENTED** [review]
1. There would be a memory problem in configuration with small DRAM and large number of CF (such as XMCyber / Flink) due to the static size of the buckets of  Mutexes ...  
2. we need to emphasis  the fact that the user should change the number of buckets if she needs to work on a restricted memory environment. 
3. Please add comments  ....

**Comment by ayulas** [comment]
fixing the build issue

**Review by hilikspdb — APPROVED** [review]

**Pull request merged**
