### PR TITLE
Export GetFlushReasonString/GetCompactionReasonString in listener.h

### PR DESCRIPTION
**Pull request by git-hulk**
The GetFlushReasonString/GetCompactionReasonString are exported in rocksdb(PR [#11778](https://github.com/facebook/rocksdb/pull/11778))
and Apache Kvrocks would like to use them to avoid copying those reason strings: https://github.com/apache/kvrocks/pull/1962

### CODE REVIEW

**Comment by ofriedma** [comment]
@git-hulk Thank you for contributing! Can you please rebase?

Thank you

**Comment by git-hulk** [comment]
@ofriedma Done

**Review by ofriedma — APPROVED** [review]
LGTM

**Comment by git-hulk** [comment]
@ofriedma Should I worry about this CI failure?

**Comment by ofriedma** [comment]
> @ofriedma Should I worry about this CI failure?
@git-hulk 
no, after it will be merged i will merge it , and your commit will be added to our next version as well, thanks

**Comment by git-hulk** [comment]
> > @ofriedma Should I worry about this CI failure?
> > @git-hulk
> > no, it is related to another issue, and your commit will be added to our next version as well, thanks

Thank you!

**Review by ofriedma — APPROVED** [review]

**Comment by ofriedma** [comment]
@git-hulk could you please resolve the conflicts?
thanks

**Review by ofriedma — APPROVED** [review]

**Pull request merged**
