### PR TITLE
memory reporting

### PR DESCRIPTION
**Pull request by ofriedma**
Add arena stats, count BlockFetcher allocations, print db memory stats to logs
fixes: [#481](https://github.com/speedb-io/speedb/issues/481)

### CODE REVIEW

**Comment by ofriedma** [comment]
@speedbmike , Changed from unordered_map to vector + enum

**Review by speedbmike — DISMISSED** [review]

**Comment by ofriedma** [comment]
@speedbmike please re-review

**Review by speedbmike — DISMISSED** [review]

**Comment by ofriedma** [comment]
@speedbmike please review, there was no conflicts for the rebase

**Comment by ofriedma** [comment]
@speedbmike please approve

**Review by Guyme — APPROVED** [review]

**Review by speedbmike — DISMISSED** [review]

**Review by speedbmike — DISMISSED** [review]

**Comment by ofriedma** [comment]
@Yuval-Ariel @Guyme  @maxb-io it is failing on Check license for CMakeLists.txt and build_detect_platform is it necessary for these files?

**Comment by ofriedma** [comment]
@Guyme @Yuval-Ariel ?

**Comment by Yuval-Ariel** [comment]
no idea

**Review by udi-speedb — DISMISSED** [review]

**Review by udi-speedb — APPROVED** [review]

**Review by speedbmike — APPROVED** [review]

**Pull request merged**
