### PR TITLE
options: Forward declare WriteBufferManager

### LINKED ISSUE #279: Including instrumented_mutex.h leads to compilation errors
When adding an include of instrumented_mutex.h in write_buffer_manager.h compilation fails:
```
#include "rocksdb/cache.h"
#include "monitoring/instrumented_mutex.h"

namespace ROCKSDB_NAMESPACE {
class CacheReservationManager;
```

When adding the same to the write_buffer_manager.cpp compilation passes. This will probably happen with other header files, I just stumbled on this while modifying write_buffer_manager.h.
This implies some issue somewhere in the include chain:
```
udi@udi-speedb:~/speedb-oss-OTHER$ make memtable/write_buffer_manager.o
$DEBUG_LEVEL is 1
Makefile:165: Warning: Compiling in debug mode. Don't use the resulting binary in production
* GEN     make_config.mk
  CC       memtable/write_buffer_manager.o
In file included from ./port/port_posix.h:16,
                 from ./port/port.h:18,
                 from ./monitoring/statistics.h:16,
                 from ./monitoring/instrumented_mutex.h:8,
                 from ./include/rocksdb/write_buffer_manager.h:22,
                 from memtable/write_buffer_manager.cc:10:
./include/rocksdb/options.h:886:19: error: ‘WriteBufferManager’ was not declared in this scope
  886 |   std::shared_ptr<WriteBufferManager> write_buffer_manager = nullptr;
      |                   ^~~~~~~~~~~~~~~~~~
./include/rocksdb/options.h:886:37: error: template argument 1 is invalid
  886 |   std::shared_ptr<WriteBufferManager> write_buffer_manager = nullptr;
      |                                     ^
./include/rocksdb/options.h:886:62: error: cannot convert ‘std::nullptr_t’ to ‘int’ in initialization
  886 |   std::shared_ptr<WriteBufferManager> write_buffer_manager = nullptr;
      |                                                              ^~~~~~~
make: *** [Makefile:2422: memtable/write_buffer_manager.o] Error 1
```

As a workaround/patch, I managed to resolve the compilation issue of write_buffer_manager file by forward declaring WriteBufferManager:
```
#include "rocksdb/cache.h"
namespace ROCKSDB_NAMESPACE {
class WriteBufferManager;

}
#include "monitoring/instrumented_mutex.h"
```
However, that causes failure of multiple other files including write_buffer_manager.h

### PR DESCRIPTION
**Pull request by AmnonHanuhov**
Fixes #279

### CODE REVIEW

**Comment by AmnonHanuhov** [comment]
@Yuval-Ariel

**Review by udi-speedb — DISMISSED** [review]

**Comment by AmnonHanuhov** [comment]
> @AmnonHanuhov - Please add the issue# to the commit message's title. Also, the commit message is not clear enough IMO.

I think the title describes exactly what I did, which is Forward declare WriteBufferManager in the options header. Which info is missing in your opinion? 
However, following your comment I added a small explanation to why this is necessary in the description of the commit.

**Comment by udi-speedb** [comment]
@AmnonHanuhov - Please have the issue number in parentheses. If it's not clear, please see other commits. Thanks

**Comment by Yuval-Ariel** [comment]
its fine, i can edit the commit msg when im merging. @udi-speedb , plz approve if there isnt anything else

**Comment by udi-speedb** [comment]
@Yuval-Ariel Nothing else

**Review by udi-speedb — APPROVED** [review]

**Pull request merged**
