### PR TITLE
dont use AVX512 with asan

### PR DESCRIPTION
**Pull request by Yuval-Ariel**

### CODE REVIEW

**Comment by Yuval-Ariel** [comment]
the problem doesnt reproduce with this branch

**Comment by udi-speedb** [comment]
@Yuval-Ariel Please add a comment explaining why you avoid using AVX512 when MUST_FREE_HEAP_ALLOCATIONS (== ASAN).

**Comment by Yuval-Ariel** [comment]
> @Yuval-Ariel Please add a comment explaining why you avoid using AVX512 when MUST_FREE_HEAP_ALLOCATIONS (== ASAN).

right you are, done

**Review by udi-speedb — APPROVED** [review]

**Comment by mrambacher** [comment]
Do we understand why this happens on the Speedb code and is not seen in Rocks?  Is it a different test suite or something different?

**Comment by udi-speedb** [comment]
> Do we understand why this happens on the Speedb code and is not seen in Rocks? Is it a different test suite or something different?

Unless I am mistaken, it does happen in RocksDB as well. This is a workaround that would let us test with ASAN. We should open an issue for RocksDB.
@Yuval-Ariel - Please confirm or correct me as applicable. Thanks

**Comment by Yuval-Ariel** [comment]
yes, @udi-speedb  is correct.

**Pull request merged**
