### PR TITLE
generic switch memtable 

### PR DESCRIPTION
**Pull request by ayulas**
generic switch memtable allows the ability to pre create memtable that allocated memory as part of the constructor
this will reduce the penelty time of switch mutable memtable which by definition will effect write flow

### CODE REVIEW

**Comment by ayulas** [comment]
@Yuval-Ariel this is the PR for the generic switch memtable. pls run QA for this . tnx

**Comment by Yuval-Ariel** [comment]
unit tests fail in options/customizable_test.cc - LoadCustomizableTest.LoadMemTableRepFactoryTest

**Review by Yuval-Ariel — APPROVED** [review]

**Comment by Yuval-Ariel** [comment]
can you add an issue number to the commit?

**Comment by Yuval-Ariel** [comment]
LoadCustomizableTest.LoadMemTableRepFactoryTest still fails

**Comment by ayulas** [comment]
@Yuval-Ariel  added a better way to handle the memtable factory destructor. pls retest

**Review by Yuval-Ariel — APPROVED** [review]

**Pull request merged**
